export const texts = {
  appName: 'Weivo',
  tabs: {
    profile: 'Profile',
    home: 'Home',
    explore: 'Explore',
    add: 'Add',
  },
  profile: {
    title: 'Profile',
    subtitle: 'Personal data, goals, and health metrics.',
    edit: 'Edit',
    sections: {
      basics: 'Basics',
      metrics: 'Health metrics',
      goal: 'Goal',
      preferences: 'Preferences',
      support: 'Support',
    },
    fields: {
      birthDate: 'Birth date',
      sex: 'Sex',
      age: 'Age',
      height: 'Height',
      currentWeight: 'Current weight',
      bmi: 'BMI',
      calories: 'Calories',
      caloriesMaintenance: 'Maintenance',
      caloriesTarget: 'Target',
      activity: 'Activity',
      goalType: 'Goal type',
      goalTarget: 'Target weight',
      goalRate: 'Weekly pace',
      goalRange: 'Target range',
      prediction: 'Prediction',
      units: 'Units',
      language: 'Language',
      theme: 'Theme',
      feedback: 'Feedback',
    },
    values: {
      notSet: 'Not set',
      unitsMetric: 'Metric (kg, cm)',
      unitsImperial: 'Imperial (lb, ft)',
      languageSoon: 'Soon',
      themeSoon: 'Soon',
      goalLose: 'Lose weight',
      goalGain: 'Gain weight',
      goalMaintain: 'Maintain',
      feedbackLink: 'Telegram',
      sexMale: 'Male',
      sexFemale: 'Female',
      caloriesMaintenance: 'Maintenance',
      caloriesTarget: 'Target',
      inRange: 'In range',
      activitySedentary: 'Sed',
      activityLight: 'Light',
      activityModerate: 'Mod',
      activityActive: 'Active',
      activityVeryActive: 'V-Act',
      activitySedentaryDesc: 'Desk work, minimal movement.',
      activityLightDesc: 'Light walks 1–2x per week.',
      activityModerateDesc: 'Training 2–3x per week.',
      activityActiveDesc: 'Training 4–5x per week.',
      activityVeryActiveDesc: 'Hard training, physical job.',
    },
  },
  profileEdit: {
    title: 'Edit profile',
    subtitle: 'Update your personal data and goals.',
    birthDate: 'Birth date',
    birthDatePlaceholder: 'Select date',
    sex: 'Sex',
    height: 'Height (cm)',
    activity: 'Activity level',
    goalType: 'Goal type',
    goalTarget: 'Target weight (kg)',
    goalRate: 'Weekly pace (kg)',
    goalRange: 'Target range (kg)',
    units: 'Units',
    currentWeight: 'Current',
    save: 'Save',
    cancel: 'Cancel',
  },
  modal: {
    title: 'New weigh-in',
    subtitle: "Add today's value and optional mood.",
    placeholderWeight: '0.0',
    moodLabel: 'Mood (optional)',
    cancel: 'Cancel',
    save: 'Save',
    addEntryTitle: 'Add entry',
  },
  home: {
    tagline: 'Weight journey - steady, honest, real',
    currentWeight: 'Current weight',
    trendingDown: 'Trending down',
    trendingUp: 'Trending up',
    lowest: 'Lowest',
    highest: 'Highest',
    entries: 'Entries',
    deltaSuffix: 'kg / 10 days',
    goal: 'Goal',
    eta: 'ETA',
    bmi: 'BMI',
    units: {
      kg: 'kg',
      days: 'days',
    },
  },
  chart: {
    title: 'Weight Flow',
    subtitleSuffix: 'days - daily log',
    start: 'Start',
    latest: 'Latest',
    unit: 'kg',
  },
  entries: {
    title: 'All entries',
    recordsSuffix: 'records',
    dailyLog: 'Daily log',
    deltaZero: '0.0',
    unit: 'kg',
    clearAll: 'Clear all',
    clearAllTitle: 'Clear all entries?',
    clearAllMessage: 'This will permanently remove every saved weigh-in.',
    clearAllConfirm: 'Clear',
    clearAllCancel: 'Cancel',
    deleteTitle: 'Delete entry?',
    deleteMessage: 'This entry will be removed permanently.',
    deleteConfirm: 'Delete',
    deleteCancel: 'Cancel',
  },
  symbols: {
    plus: '+',
  },
  moods: {
    happy: '🙂',
    neutral: '😐',
    sad: '😔',
    angry: '😠',
  },
  greeting: {
    wave: '👋',
  },
};
