export const GOAL_PROGRESS_SIZE = 84
export const GOAL_PROGRESS_STROKE = 8
export const GOAL_PROGRESS_CHECK_STROKE = 4
export const GOAL_PROGRESS_SUCCESS_DELAY_MS = 450
export const GOAL_PROGRESS_SUCCESS_DURATION_MS = 650
export const GOAL_PROGRESS_PROGRESS_DURATION_MS = 1200
