export const colors = {
  ink: '#1B1B1B',
  inkStrong: '#101010',
  inkSoft: '#9A7E69',
  inkMuted: '#5A4636',
  inkMutedAlt: '#5D4B3A',
  inkMutedLight: '#6B5647',
  inkWarm: '#6A7D7E',
  inkAccent: '#B8A594',
  cream: '#EFE4D7',
  creamLight: '#F7F1E9',
  creamLighter: '#F8F2EA',
  creamWarm: '#F5EFE7',
  creamCard: '#FAF7F2',
  creamLine: '#E5DBCF',
  creamHint: '#DAD0C4',
  creamMuted: '#E3D6C7',
  creamHandle: '#E0D5C9',
  highlight: '#F7EFE6',
  highlightAlt: '#F6F0E9',
  accentGold: '#D8B18A',
  accentOrange: '#C86B33',
  accentOrangeDark: '#B96A2C',
  accentOrangeSoft: '#F4B183',
  accentTeal: '#2E5C56',
  white: '#FFFFFF',
  link: '#0a7ea4',
  lightText: '#11181C',
  lightBackground: '#fff',
  lightIcon: '#687076',
  darkText: '#ECEDEE',
  darkBackground: '#151718',
  darkIcon: '#9BA1A6',
  overlay: 'rgba(20, 16, 12, 0.25)',
  glow: 'rgba(16,16,16,0.12)',
};

export const darkColors = {
  ink: '#F5EFE6',
  inkStrong: '#0F0D0B',
  inkSoft: '#C9B8A7',
  inkMuted: '#B2A08F',
  inkMutedAlt: '#B9A695',
  inkMutedLight: '#C7B5A5',
  inkWarm: '#9FB3B4',
  inkAccent: '#8C7B6C',
  cream: '#171412',
  creamLight: '#1F1B18',
  creamLighter: '#24201D',
  creamWarm: '#211C18',
  creamCard: '#26211E',
  creamLine: '#2C2622',
  creamHint: '#C9B8A7',
  creamMuted: '#D4C4B4',
  creamHandle: '#3A332E',
  highlight: '#F7EFE6',
  highlightAlt: '#EADFD4',
  accentGold: '#D8B18A',
  accentOrange: '#E08C52',
  accentOrangeDark: '#CC7B40',
  accentOrangeSoft: '#F2B98B',
  accentTeal: '#3E7E77',
  white: '#FFFFFF',
  link: '#7EC1D6',
  lightText: '#11181C',
  lightBackground: '#fff',
  lightIcon: '#687076',
  darkText: '#ECEDEE',
  darkBackground: '#151718',
  darkIcon: '#9BA1A6',
  overlay: 'rgba(8, 6, 4, 0.6)',
  glow: 'rgba(0,0,0,0.35)',
};

export const roseColors = {
  ...colors,
  ink: '#2D2425',
  inkStrong: '#1B1314',
  inkSoft: '#9B7A7E',
  inkMuted: '#6C4F53',
  inkMutedAlt: '#6A4E52',
  inkMutedLight: '#7A5B5F',
  inkWarm: '#8A7C7F',
  inkAccent: '#BFA4A8',
  cream: '#F2E4E6',
  creamLight: '#F8EEF0',
  creamLighter: '#F9F2F3',
  creamWarm: '#F3E6E8',
  creamCard: '#FBF5F6',
  creamLine: '#E7D6D9',
  creamHint: '#E1CED1',
  creamMuted: '#E6D5D8',
  creamHandle: '#E0D0D3',
  highlight: '#FBF2F3',
  highlightAlt: '#F8ECEE',
  accentGold: '#EA8C98',
  accentOrange: '#D34C62',
  accentOrangeDark: '#C24355',
  accentOrangeSoft: '#F4A0B0',
  accentTeal: '#5A8B8A',
};

export const skyColors = {
  ...colors,
  ink: '#23303A',
  inkStrong: '#161F27',
  inkSoft: '#8AA0B3',
  inkMuted: '#506578',
  inkMutedAlt: '#4E6375',
  inkMutedLight: '#5C7386',
  inkWarm: '#6A8796',
  inkAccent: '#97AFC0',
  cream: '#E6EFF6',
  creamLight: '#EEF4FA',
  creamLighter: '#F3F7FB',
  creamWarm: '#E3ECF4',
  creamCard: '#F7FAFD',
  creamLine: '#D3DEE9',
  creamHint: '#CBD7E2',
  creamMuted: '#D8E3ED',
  creamHandle: '#D1DCE7',
  highlight: '#F7FAFD',
  highlightAlt: '#EEF5FB',
  accentGold: '#86B4D6',
  accentOrange: '#3C7FB3',
  accentOrangeDark: '#33709E',
  accentOrangeSoft: '#8EC1E6',
  accentTeal: '#2D6E80',
};

export const mintColors = {
  ...colors,
  ink: '#25332E',
  inkStrong: '#18231F',
  inkSoft: '#7E9A8E',
  inkMuted: '#4B6459',
  inkMutedAlt: '#4A6358',
  inkMutedLight: '#5A7569',
  inkWarm: '#6F8A7F',
  inkAccent: '#96AF9F',
  cream: '#E6F2EC',
  creamLight: '#EFF7F3',
  creamLighter: '#F4FAF7',
  creamWarm: '#E3EFEA',
  creamCard: '#F7FBF9',
  creamLine: '#D2E3DB',
  creamHint: '#C8DAD1',
  creamMuted: '#D9E9E1',
  creamHandle: '#D1E2DA',
  highlight: '#F6FBF8',
  highlightAlt: '#EDF7F2',
  accentGold: '#67D8A7',
  accentOrange: '#28C07C',
  accentOrangeDark: '#1FA56A',
  accentOrangeSoft: '#8DE9C1',
  accentTeal: '#2D7C68',
};

export type ThemeColors = typeof colors;

export const themes = {
  light: colors,
  dark: darkColors,
  rose: roseColors,
  sky: skyColors,
  mint: mintColors,
};

export const themeColors = {
  light: {
    text: colors.ink,
    background: colors.cream,
    tint: colors.link,
    icon: colors.inkMuted,
    tabIconDefault: colors.inkAccent,
    tabIconSelected: colors.ink,
  },
  dark: {
    text: darkColors.ink,
    background: darkColors.cream,
    tint: darkColors.link,
    icon: darkColors.inkMuted,
    tabIconDefault: darkColors.inkMuted,
    tabIconSelected: darkColors.ink,
  },
  rose: {
    text: roseColors.ink,
    background: roseColors.cream,
    tint: roseColors.link,
    icon: roseColors.inkMuted,
    tabIconDefault: roseColors.inkAccent,
    tabIconSelected: roseColors.ink,
  },
  sky: {
    text: skyColors.ink,
    background: skyColors.cream,
    tint: skyColors.link,
    icon: skyColors.inkMuted,
    tabIconDefault: skyColors.inkAccent,
    tabIconSelected: skyColors.ink,
  },
  mint: {
    text: mintColors.ink,
    background: mintColors.cream,
    tint: mintColors.link,
    icon: mintColors.inkMuted,
    tabIconDefault: mintColors.inkAccent,
    tabIconSelected: mintColors.ink,
  },
};
