export const colors = {
  ink: '#1B1B1B',
  inkStrong: '#101010',
  inkSoft: '#9A7E69',
  inkMuted: '#5A4636',
  inkMutedAlt: '#5D4B3A',
  inkMutedLight: '#6B5647',
  inkWarm: '#6A7D7E',
  inkAccent: '#B8A594',
  cream: '#EFE4D7',
  creamLight: '#F7F1E9',
  creamLighter: '#F8F2EA',
  creamWarm: '#F5EFE7',
  creamCard: '#FAF7F2',
  creamLine: '#E5DBCF',
  creamHint: '#DAD0C4',
  creamMuted: '#E3D6C7',
  creamHandle: '#E0D5C9',
  highlight: '#F7EFE6',
  highlightAlt: '#F6F0E9',
  accentGold: '#D8B18A',
  accentOrange: '#C86B33',
  accentOrangeDark: '#B96A2C',
  accentOrangeSoft: '#F4B183',
  accentTeal: '#2E5C56',
  white: '#FFFFFF',
  link: '#0a7ea4',
  lightText: '#11181C',
  lightBackground: '#fff',
  lightIcon: '#687076',
  darkText: '#ECEDEE',
  darkBackground: '#151718',
  darkIcon: '#9BA1A6',
  overlay: 'rgba(20, 16, 12, 0.25)',
  glow: 'rgba(16,16,16,0.12)',
};

export const themeColors = {
  light: {
    text: colors.lightText,
    background: colors.lightBackground,
    tint: colors.link,
    icon: colors.lightIcon,
    tabIconDefault: colors.lightIcon,
    tabIconSelected: colors.link,
  },
  dark: {
    text: colors.darkText,
    background: colors.darkBackground,
    tint: colors.white,
    icon: colors.darkIcon,
    tabIconDefault: colors.darkIcon,
    tabIconSelected: colors.white,
  },
};
