import { StyleSheet } from 'react-native'
import type { ThemeColors } from '@/theme'
import { fontSizes, letterSpacings } from '@/theme/typography'
import { radii } from '@/theme/radii'
import { spacing } from '@/theme/spacing'

export const createBuddiesStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.cream, paddingHorizontal: spacing.xl, paddingTop: spacing.xl },
    content: { paddingBottom: spacing.xxlLarge, gap: spacing.xl },
    hero: {
      backgroundColor: colors.creamLight,
      borderRadius: radii.card,
      borderWidth: 1,
      borderColor: colors.creamLine,
      padding: spacing.xxl,
      gap: spacing.md,
    },
    badge: {
      alignSelf: 'flex-start',
      backgroundColor: colors.highlight,
      color: colors.inkStrong,
      borderRadius: radii.full,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.xs,
      fontSize: fontSizes.xs,
      textTransform: 'uppercase',
      letterSpacing: letterSpacings.md,
      overflow: 'hidden',
    },
    title: { fontSize: fontSizes.xxl, color: colors.ink },
    subtitle: { fontSize: fontSizes.md, color: colors.inkMuted, lineHeight: 22 },
    actions: { flexDirection: 'row', gap: spacing.md },
    action: { flex: 1 },
    section: {
      backgroundColor: colors.creamLight,
      borderRadius: radii.card,
      borderWidth: 1,
      borderColor: colors.creamLine,
      padding: spacing.xl,
      gap: spacing.lg,
    },
    sectionTitle: {
      fontSize: fontSizes.md,
      color: colors.inkMutedLight,
      textTransform: 'uppercase',
      letterSpacing: letterSpacings.xl,
    },
    step: { flexDirection: 'row', gap: spacing.md, alignItems: 'flex-start' },
    stepNum: {
      width: 24,
      height: 24,
      borderRadius: radii.full,
      backgroundColor: colors.inkStrong,
      color: colors.highlight,
      textAlign: 'center',
      overflow: 'hidden',
      fontSize: fontSizes.sm,
      lineHeight: 24,
    },
    stepText: { flex: 1, fontSize: fontSizes.md, lineHeight: 21, color: colors.ink },
    rewardTitle: { fontSize: fontSizes.lg, color: colors.ink },
    rewardText: { fontSize: fontSizes.md, color: colors.inkMuted, lineHeight: 21 },
    rewardHint: {
      fontSize: fontSizes.sm,
      color: colors.inkSoft,
      textTransform: 'uppercase',
      letterSpacing: letterSpacings.sm,
    },
    searchRow: { flexDirection: 'row', gap: spacing.md, alignItems: 'center' },
    searchInput: { flex: 1 },
    helper: { fontSize: fontSizes.sm, color: colors.inkMuted },
    list: { gap: spacing.sm },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.creamCard,
      borderWidth: 1,
      borderColor: colors.creamLine,
      borderRadius: radii.lg,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
      gap: spacing.md,
    },
    rowMain: { flex: 1, gap: spacing.xs },
    rowTitle: { fontSize: fontSizes.md, color: colors.ink },
    rowMeta: { fontSize: fontSizes.sm, color: colors.inkMuted },
    rowActions: { flexDirection: 'row', gap: spacing.sm },
    miniBtn: { minWidth: 88 },
    emptyText: { fontSize: fontSizes.md, color: colors.inkMuted },
    errorText: { color: colors.accentOrange, fontSize: fontSizes.sm },
  })
